name: Resize
version: 1.2.2
main: com.resize.Resize
author: portal_gum
api-version: 1.20

softdepend: [LuckPerms, WorldGuard, PlaceholderAPI]

commands:
  resize:
    usage: /resize <size> [player]
    description: allows changing the player’s size

permissions:
  resize.*:
    description: gives access to all Resize plugin permissions
    default: op
    children:
      resize.resize: true
      resize.info: true
      resize.info.other: true
      resize.reload: true
      resize.admin: true
      resize.mob: true
      resize.resize.other: true

  resize.resize:
    description: allows using the /resize command
    default: true

  resize.info:
    description: allows using /resize info
    default: true

  resize.info.other:
    description: allows viewing other players' size info
    default: op

  resize.resize.other:
    description: allows changing other players' size
    default: op

  resize.mob:
    description: allows changing mob size
    default: op

  resize.admin:
    description: administrator permission (no limits)
    default: op

  resize.reload:
    description: allows reloading the plugin configuration
    default: op
